### CURSOR PAGINATION & SLICE (SCROLL) FIRST
GET http://localhost:8080/api/posts?size=10
Accept: application/json

### CURSOR PAGINATION & SLICE (SCROLL)
GET http://localhost:8080/api/posts?size=10&nextCursor=991
Accept: application/json

### CURSOR PAGINATION & SLICE & ORDER BY (SCROLL)
GET http://localhost:8080/api/posts?size=10&sort=createdDate,desc
Accept: application/json

### OFFSET & SLICE (SCROLL)
GET http://localhost:8080/api/posts/offset?size=10&page=0&sort=createdDate,desc
Accept: application/json